export interface Env {
  POSTGRES_URL?: string;
  POSTGRES_USER?: string;
  POSTGRES_HOST?: string;
  SUPABASE_JWT_SECRET?: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY?: string;
  POSTGRES_PRISMA_URL?: string;
  POSTGRES_PASSWORD?: string;
  POSTGRES_DATABASE?: string;
  SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_URL?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  POSTGRES_URL_NON_POOLING?: string;
}

export const env: Env = {
  POSTGRES_URL: process.env.POSTGRES_URL,
  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_HOST: process.env.POSTGRES_HOST,
  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,
  SUPABASE_URL: process.env.SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
};
